### ISSUE TITLE
Typing across modules.

### ISSUE THREAD

**Issue by pentacular** [orzechowskid/eslint-plugin-typelint#24]
**what would you like to see added?**

Given an import like
```
import { Foo } from './Foo';
```
There doesn't seem to be a reasonable way to type it.

One option might be to support type declarations on imports like so:
```
/** @type {function(boolean): number} */
import { Foo } from './Foo';
```

But this will introduce a fragile dependency between the actual definition and the type declaration at the import sites.

Perhaps some form of whole-program analysis is required.

**Comment by pentacular** [comment]
Ok, I think I see the problem.

resolveTypeForCallExpression is bypassing resolveTypeForNodeIdentifier and trying to extract the return type directly from a comment attached to the lexical definition.

Instead I think it should resolveTypeForNodeIdentifier to produce a function type and decompose it to produce the return type.

**Comment by orzechowskid** [comment]
> So perhaps this ought to be working already.

"ought to" is a little optimistic, as you're finding out :)  but yes there's some code in here which should allow for a scenario like this to be analyzed:

```javascript
// types.js

/**
 * @typedef {object} Person
 * @property {string} name
 * @property {int} age
 */

// code.js

/** @typedef {import('./types').Person */
const myPerson = { name: 'Alice', age: 20 };
```

it's not mentioned in the docs because (a) I don't believe that `import` is valid JSDoc, and (b) I couldn't come up with a satisfactory way of testing it so I couldn't ensure it wouldn't break as changed were made to the plugin.

neither the existing unit tests nor eslint's [recommended way of unit-testing your plugins](https://eslint.org/docs/developer-guide/nodejs-api#ruletester) seem to handle test cases involving more than one source file.

> resolveTypeForCallExpression is bypassing resolveTypeForNodeIdentifier and trying to extract the return type directly from a comment attached to the lexical definition.
> 
> Instead I think it should resolveTypeForNodeIdentifier to produce a function type and decompose it to produce the return type.

good catch, that's probably true

**Comment by pentacular** [comment]
What I see in the code is that this ought to work

```
// types.js
/** @type {boolean} */
export let foo = true;
```
```
// code.js
import { foo } from './types';
// foo carries @type {boolean} with it.
```

My proposal for @typedef would be that they be qualified, and travel implicitly over import bridges.

So the following scenario would pass typecheck.
```
// types.js
/** @typedef {boolean} bar */
/** @type {bar} */
export let foo = true;
```
```
// code.js
import { foo } from './types';
// foo carries @type {types/bar} with it.
// import from './types' carries @typedef types/bar with it.

/** @type function(types/bar): undefined */
const bar = (x) => undefined;

bar(foo);
```

Not sure how the qualification ought to work, but I seem to remember something about namespaces in jsdoc.

I think the rest of the problem is about getting return and parameter information via Type rather than direct comment introspection.

**Comment by orzechowskid** [comment]
hm, ok.  that is (intended to be) supported as well, but again I don't have any tests yet for cross-file type resolution and wouldn't be surprised if it broke at some point.  I'll see what I can do about it when I get some free time.

**Comment by orzechowskid** [comment]
should be fixed by https://github.com/orzechowskid/eslint-plugin-typelint/pull/25 which I just merged to master.  bonus: I figured out cross-file tests, so there's one in assignment-types-must-match.test.js now :+1:
