### ISSUE TITLE
support return values sniffed from @type {Function():<type>}

### ISSUE THREAD

**Issue by orzechowskid** [orzechowskid/eslint-plugin-typelint#4]
**what would you like to see added?**

function return value types can be specified in a couple of ways.

**Comment by pentacular** [comment]
Yes, I'd very much like to see support for something like ...

/** @type {function(a: string, b: boolean): number}  */

Inline parameter type comments would be also great.

**Comment by pentacular** [comment]
I had a look around and found:

https://github.com/artdecocode/parser/blob/master/test/spec/default.js
which is published under npm @typedefs/parser

This would do what I want, but I'm not sure it does what you're after.

ptal

**Comment by orzechowskid** [comment]
this test case should pass with my latest commit to master:

```javascript

/**
 * @type {function(number): number[]}
 */
const toArrayFromRgbInt = (rgbInt) => {
  return [(rgbInt >> 16) & 0xff, (rgbInt >> 8) & 0xff, (rgbInt >> 0) & 0xff];
}

/**
 * @type {function(number): number[]}
 */
const toEntryFromRgbInt = (rgbInt) => {
  const rgb = toArrayFromRgbInt(rgbInt);
  return rgb;
};
```

and this test case should fail with the appropriate error message:

```javascript
/**
 * @type {function(number): number[]}
 */
const toArrayFromRgbInt = (rgbInt) => {
  return [(rgbInt >> 16) & 0xff, (rgbInt >> 8) & 0xff, (rgbInt >> 0) & 0xff];
}

// changed jsdoc block below

/**
 * @type {function(number): string[]}
 */
const toEntryFromRgbInt = (rgbInt) => {
  const rgb = toArrayFromRgbInt(rgbInt);
  return rgb;
};
```

**Comment by orzechowskid** [comment]
that parser library looks interesting but it uses GCC syntax which I understand is slightly different from JSDoc syntax?  tbh I'm not sure the best course to take here.

**Comment by pentacular** [comment]
No idea :)

But if /** @type {function(number): number[]} */ works, that's good enough for me. :)

How do you feel about a new npm release at this point?

That would make it easier to try out on an actual project.
