### ISSUE TITLE
TypeError: Cannot read property 'comments' of undefined on example from README

### ISSUE THREAD

**Issue by pentacular** [orzechowskid/eslint-plugin-typelint#9]
**snippet of incorrectly-linted code**
/**
 * @param {boolean} myBool
 * @return {string}
 */
function booleanIsTrue(myBool) {
  return myBool ? "yes" : "no";
}

/** @type {number} */
const x = booleanIsTrue(true);
// eslint message:
// "can't assign type string to variable of type number"

/** @type {string} */
const y = booleanIsTrue(true);
// correctly-typed, so no eslint message! 🎉

const z = booleanIsTrue(false);
// also no eslint message, since `z` has no declared type 🤔 (you should fix that!)

**expected behavior**
Expected the same output as in the documentation for this documented example.

npm run lint index.js

> typelint-test@1.0.0 lint typelint-test
> eslint "index.js"

Oops! Something went wrong! :(

ESLint: 7.2.0

TypeError: Cannot read property 'comments' of undefined
Occurred while linting typelint-test/index.js:10

**typelint config**
eslint --print-config  "index.js"

{
  "env": {},
  "globals": {},
  "parser": null,
  "parserOptions": {
    "ecmaFeatures": {
      "impliedStrict": true
    },
    "ecmaVersion": 8,
    "loc": true
  },
  "plugins": [
    "@orzechowskid/typelint",
    "jsdoc"
  ],
  "rules": {
    "@orzechowskid/typelint/assignment-types-must-match": [
      "error"
    ]
  },
  "settings": {},
  "ignorePatterns": []
}

**package versions**
please include the versions of eslint and typelint you're using.
  "devDependencies": {
    "@orzechowskid/eslint-plugin-typelint": "^0.3.0",
    "eslint": "^7.2.0",
    "eslint-plugin-jsdoc": "^27.0.6"
  }

**issue checklist**

please replace `[ ]` with `[x]` just to make double sure that you filled out all the above sections.

- [x] I included the smallest-possible code snippet above
- [x] I provided the typelint config for the applicable rule above
- [ ] I marked this checkbox as done because I'm not paying attention
- [x] I described the expected behavior above
- [x] I provided the versions of eslint and typeline currently in use

thanks for taking the time to follow the above steps; it really helps me avoid a lot of back-and-forth and allows me to locate and fix the issue more quickly!

**Comment by pentacular** [comment]
I've been looking for something like this project for a while, but I haven't been able to get it to work so far.

It would be great if there were an example project that is set up to use it, as a reference.

**Comment by orzechowskid** [comment]
oh wow, someone actually found and tried out this library!  :)

I just published 0.3.2 which has some updates that should fix this particular issue and some tests to ensure that it doesn't happen again (because geez what a black eye for me).

thanks -

**Comment by pentacular** [comment]
I've cloned and using npm link to patch master into my test project.

Now

```
/**
 * @param {number} rbgInt
 * @return {number[]}
 */
function toArrayFromRgbInt (rgbInt) {
  return [(rgbInt >> 16) & 0xff, (rgbInt >> 8) & 0xff, (rgbInt >> 0) & 0xff];
}

/**
 * @param {number} rbgInt
 * @return {number[]}
 */
function toEntryFromRgbInt (rgbInt) {
  const rgb = toArrayFromRgbInt(rgbInt);
  return rgb;
};
```

is producing

```
Oops! Something went wrong! :(

ESLint: 7.2.0

TypeError: Type is not iterable (cannot read property Symbol(Symbol.iterator))
Occurred while linting /github10/typelint-test/testf.js:14
    at /github10/eslint-plugin-typelint/src/utils.js:594:24
    at Array.map (<anonymous>)
    at getArgumentsForFunction (/github10/eslint-plugin-typelint/src/utils.js:588:45)
    at CallExpression (/github10/eslint-plugin-typelint/src/rules/function-args-length-must-match.js:13:38)
    at /github10/typelint-test/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/github10/typelint-test/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/github10/typelint-test/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/github10/typelint-test/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/github10/typelint-test/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
```

I've confirmed that /github10/eslint-plugin-typelint/src/utils.js contains your new code
e.g.
```
    const params = extractParams(comment, context);

    //    console.log(`binding:`, binding);
    //    console.log(`params:`, params);
    return binding.definition.parent.params.map(function(p) {

```
So it should be representative of the latest master.

Let me know if you'd like me to open new issues for each of these cases.

Otherwise I can just pile them up here, since they should have the same configuration.

**Comment by orzechowskid** [comment]
yeah, feel free to pile stuff here and I'm glad to keep playing whack-a-mole when I have the time.

I noticed that your variables are `rgbInt` but your jsdoc is `rbgInt`; that was what was causing your immediate problem (and eslint-plugin-jsdoc may be of use to you for cases like these) but even with that typo fixed the code would still throw an error.  since you said you cloned the repo, I pushed a fix to `master` instead of publishing to npm; take a look when you have the chance.

thanks again!

**Comment by pentacular** [comment]
```
   6:3   error  returning undefined from a function declared to return number[]                          @orzechowskid/typelint/function-return-type-must-match
  14:15  error  type number expected for parameter 0 in call to toArrayFromRgbInt but number[] provided  @orzechowskid/typelint/function-args-types-must-match
  15:3   error  returning undefined from a function declared to return number[]                          @orzechowskid/typelint/function-return-type-must-match
```

Thanks for catching that typo and the fix -- works nicely. :)

**Comment by pentacular** [comment]
I've been trying to type arrow function variables.

```
* @type {function(number): number[]}
```
and
```
 * @param {number} rgbInt
 * @returns {number[]}
```
on
```
/**
 * @type {function(number): number[]}
 */
const toArrayFromRgbInt = (rgbInt) => [
  (rgbInt >> 16) & 0xff,
  (rgbInt >> 8) & 0xff,
  (rgbInt >> 0) & 0xff,
];

/**
 * @type {function(number): number[]}
 */
const toEntryFromRgbInt = (rgbInt) => {
  const rgb = toArrayFromRgbInt(rgbInt);
  return rgb;
};
```

but neither form seems to work -- I get.
```
TypeError: Cannot read property 'isOfType' of undefined
    at ReturnStatement (/github10/eslint-plugin-typelint/src/rules/function-return-type-must-match.js:38:41)
```

I'm not entirely clear on how arrow functions ought to be typed using jsdoc, so I may well have that wrong.

But I guess it shouldn't be failing like that, either. :)

**Comment by pentacular** [comment]
Ok, I think I understand what's going on well enough now.

Let me know if you're interested in sorting out ArrowFunctionExpression support, otherwise I think I can put together a PR.

**Comment by pentacular** [comment]
Ah, I think I've found another problem.

```
/**
 * @param {number} rgbInt
 * @returns {string}
 */
function toArrayFromRgbInt (rgbInt) {
  return 'one';
}

/**
 * @param {number} rgbInt
 * @returns {string}
 */
function toEntryFromRgbInt (rgbInt) {
  return toArrayFromRgbInt(rgbInt);
};
```

produces

```
  14:10  error  type number expected for parameter 0 in call to toArrayFromRgbInt but string provided  @orzechowskid/typelint/function-args-types-must-match
```

I think it's resolving the type of rgbInt to the return type of the function it is a parameter of.

**Comment by pentacular** [comment]
Here's a new one:
```
const bar = () => Error('die');
```
produces
```
TypeError: Cannot read property 'parent' of undefined
```

This seems to be due to discovering a binding, with { definition: undefined }.

We can avoid the crash by testing like

```
    if (!binding) {
        return;
    }

    if (!binding.definition) {
        // Some things seem to have bindings, but no definition.
        // e.g., Error
        return;
    }

    return getArgumentsForFunctionDefinition(binding.definition.parent, context);
```

but this implies that the function accepts no arguments, which leads to a type error in the above case.

Not sure how this ought to be handled.

**Comment by pentacular** [comment]
```
binding.definition
The node that defined this binding. If this binding was not declared in the AST, binding.definition will be undefined.
```

which explains that, but for some reason
```
const bar = () => Math.abs(1);
```
works, which is slightly perplexing.

**Comment by pentacular** [comment]
This probably needs its own issue -- I think it'll require setting up types for all of the global objects.
